/**
 * ---------------------
 * 🚗🚦 Generated by nuxt-typed-router. Do not modify !
 * ---------------------
 * */

import { defineNuxtPlugin } from '#app';

export default defineNuxtPlugin((nuxtApp) => {
  const routesList = {
    authCallback: 'auth-callback',
    authCsr: 'auth-csr',
    authLogout: 'auth-logout',
    beheer: 'beheer',
    bestellingen: 'bestellingen',
    index: 'index',
    invoerSlug: 'invoer-slug',
    logout: 'logout',
    personen: 'personen',
  };

  return {
    provide: {
      typedRouter: nuxtApp.$router,
      routesList,
    },
  };
});
